### ISSUE TITLE
Mudança na morte de Gatinho e No Print

### ISSUE THREAD

**Issue by MagnoCarta** [jjoaosilva/challengeSwift#2]
Arquivo:
main.swift

Funcão:
startAplication()

Sugestão de melhora:
Trocar texto do print("Not Found About: \(userInput!)\n") por
print("Nothin was written: \(userInput!)\n")

Sugestão de melhora:
Substituir Forced Unwrawpping on let filteredText: String = removeCharactersInvalids(text: userInput!) por
if let filteredText = Optional(removeCharactersInvalids(text: userInput!)){}else {
print("Error")
}

**Comment by MagnoCarta** [comment]
By Magno e Leo !

**Comment by jjoaosilva** [comment]
Agradeço pelo feedback e essas mudanças, agora, foram corrigidas.

**Comment by MagnoCarta** [comment]
Nicee
