### ISSUE TITLE
Sugestao de Melhoria

### ISSUE THREAD

**Issue by ronaldogomes96** [jjoaosilva/challengeSwift#3]
Dupla: Bia / Ronaldo
Arquivo:
main.swiift
Descrição:
Colocar um loop infinito sobre a inicialização da função startAplication () para poder pesquisar mais de um assunto sem precisar reiniciar o programa novamente, e somente sair quando o usuário quiser.

**Comment by jjoaosilva** [comment]
Agradeço pelo seu feedback e compreendo muito bem a ideia e sua sugestão é muito bem vinda. Hoje, o script está inserido em um escopo em que se deve ser utilizado apenas uma vez, logo a feature de múltiplas pesquisas, por hora, está descartada. 

Muito obrigado pelo feedback <3
