### ISSUE TITLE
Sugestão de melhoria

### ISSUE THREAD

**Issue by patysiq** [jjoaosilva/challengeSwift#4]
Excelente aplicativo e código.

Como sugestão de melhoria do código poderia ser usado funções do Date Components para pegar a data corrente e não precisar pedir e formatar a data do usuário (a não ser que o usuário deseje pesquisar algo anterior).

**Comment by jjoaosilva** [comment]
Agradeço pelo seu feedback! Ele é muito importante pra gente!
Quero dizer que a data utilizada sempre é a do dia corrente e que o usuário não possui, hoje, a opção de inserir uma data de pesquisa.
